version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy  # ✅ Ensure DB is ready before backend starts
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always  

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ai_career_user
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ai_career_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # ✅ Ensures database is ready before backend starts
      test: ["CMD-SHELL", "pg_isready -U ai_career_user -d ai_career_db"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
