"""added mock interview-1

Revision ID: 122522205b92
Revises: d49264cb4caf
Create Date: 2025-03-23 15:10:46.091496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '122522205b92'
down_revision: Union[str, None] = 'd49264cb4caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arya_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arya_message_id'), 'arya_message', ['id'], unique=False)
    op.drop_index('ix_arya_chat_messages_id', table_name='arya_chat_messages')
    op.drop_table('arya_chat_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arya_chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='arya_chat_messages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='arya_chat_messages_pkey')
    )
    op.create_index('ix_arya_chat_messages_id', 'arya_chat_messages', ['id'], unique=False)
    op.drop_index(op.f('ix_arya_message_id'), table_name='arya_message')
    op.drop_table('arya_message')
    # ### end Alembic commands ###
